spring:
  datasource:
    url: jdbc:h2:mem:credit_application_request_system_db
    username: otavio
  #jpa:
    #hibernate:
     # ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
