CREATE TABLE customer (
  id BIGSERIAL PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  cpf VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  zip_code VARCHAR(255) NOT NULL,
  street VARCHAR(255) NOT NULL,
  house_number INTEGER NOT NULL, -- Mudei de BIGINT para INTEGER
  income NUMERIC(19, 2) NOT NULL -- Mudei de BIGINT para NUMERIC(19, 2)
);
